"""Added films table

Revision ID: 97e9bbab5354
Revises: a78d033e3505
Create Date: 2021-09-07 19:12:26.797742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e9bbab5354'
down_revision = 'a78d033e3505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('piece_number', sa.Integer(), nullable=True),
    sa.Column('piece_size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('films', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'file_size')
    op.drop_table('film_pieces')
    # ### end Alembic commands ###
