"""Added size field

Revision ID: fa9587b46e32
Revises: 97e9bbab5354
Create Date: 2021-09-08 15:28:31.026909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9587b46e32'
down_revision = '97e9bbab5354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'size')
    # ### end Alembic commands ###
